config/routes.rb
IrcUrls::Application.routes.draw do
  def type(controller, path, viewtype = true)
    interval_constraint = /((\d+)\s?(\w+)|alltime)/
    viewtype_constraint = /(list|grid)/

    scope path do
      match "recent/:viewtype", :to => "#{controller}#recent", :constraints => {:viewtype => viewtype_constraint}, :via => :get if viewtype
      match "top/:interval(/:viewtype)", :to => "#{controller}#index", :constraints => {:viewtype => viewtype_constraint}, :via => :get if viewtype
      match ":viewtype", :to => "#{controller}#index", :constraints => {:viewtype => viewtype_constraint}
      match "top/:interval", :to => "#{controller}#index", :constraints => {:interval => interval_constraint}, :via => :get
    end

    if block_given?
      yield
    else
      match "/", :to => "#{controller}#index"
    end

    resources controller, :path => path, :only => :index do
      collection do
        get :recent
      end
    end

    scope path do
      match "top", :to => "#{controller}#index", :as => "top_#{controller}", :via => :get
    end

  end

  def occurrences(&blk)
    type(:occurrences, "urls", false, &blk)
    type(:video_occurrences, "videos", &blk)
    type(:image_occurrences, "images", &blk)
    type(:media_occurrences, "media", &blk)
  end

  resource :submissions

  match "*anything", :to => redirect("http://irc-urls.net/%{anything}"), :constraints => {:subdomain => "beta"}
  match "/", :to => redirect("http://irc-urls.net/"), :constraints => {:subdomain => "beta"}

  [:images, :videaos, :media].each do |type|
    match "/#{type}/grid/recent", :to => redirect("/#{type}/recent/grid")
  end

  devise_for :users
  resource :token, :only => ["create"]
  match '/account' => 'users#show', :as => 'account'
  match 'help/installation' => "help#installation", :as => "help_installation"

  resources :trackings
  [:url, :image_url, :video_url].each do |type|
    resources type, :path => :url, :controller => :urls, :only => :show
  end

  resources :networks, :only => :index do
    occurrences
    resources :channels, :only => :index do
      occurrences
    end
  end

  resources :caches, :only => :show

  occurrences do
    root :to => "occurrences#index"
  end

end

app/models/channel.rb
require 'lib/slugify'

class Channel < ActiveRecord::Base
  include Slugify
  
  has_many                  :trackings, :dependent => :destroy
  has_many                  :occurrences, :dependent => :destroy
  has_many                  :users, :through => :trackings
  has_many                  :loggings, :through => :occurrences
  belongs_to                :network
  
  validates_uniqueness_of   :name,    :case_sensitive => false, :scope => :network_id
  validates_presence_of     :name
  validates_format_of       :name,    :with => /^[\!\&#]\S+$/
  validates_presence_of     :network_id
  
  scope :slugified, lambda { |column, str|
    if match = str.match(/^(\d+)-.+/)
      return {:conditions => ["#{self.table_name}.id = ?", match[1]]}
    end
    str = self.real_name(str)
    return {:conditions => ["LOWER(#{self.table_name}.#{column.to_s}) = ?", str.downcase]}
  }
  
  def self.real_name(str)
    # Add missing '#' (ex. "foo" => "#foo")
    str.gsub(/^([^#!&])/, '#\1')
  end
  
  def self.clean_name(str)
    str.gsub(/^#/,'')
  end
  
  def public_tracking_disabled?
    self.status == 'private'
  end
  
  def public?
    @public ||= !loggings.only_public.empty?
  end
  
  def to_param
    slugify_if_necessary(id, self.class.clean_name(name))
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_filter :get_channel, :except => [:index]
  
  def show
  end

  def index
    @network = Network.find_by_name(params[:network_id])
    @channels = @network.channels
  end

  private
    def get_channel
      @channel = Network.find_by_name(params[:network_id]).channels.slugified(:name, params[:id]).first
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_channel.html.erb
<p><%= link_to channel.name, [@network, channel] %></p>

app/views/channels/index.html.erb
<h1><%= title("Channels in #{@network.name}") -%></h1>
<div class="infobox">
  <h2>Channels</h2>
  <ul>
    <%- @network.public_channels.each do |channel| %>
      <li><%= link_to channel.name, network_channel_path(@network, channel) %></li>
    <%- end -%>
  </ul>
</div>

app/views/channels/show.html.erb
<h1>Channel <%= @channel.name -%> at <%= link_to @channel.network.name, @channel.network -%></h1>
<%- title("Channel #{@channel.name} at #{@channel.network.name}") -%>

<div class="infobox">
  <h2>Statistics</h2>
  <dl>
    <dt>Public URLs<dt>
    <dd>
      <%= image_tag('silk/calendar_view_week.png') -%> Last 24h <b><%= @channel.occurrences.only_public.time_scope('24hours').count -%></b>
    </dd>
    <dd>
      <%= image_tag('silk/calendar_view_week.png') -%> Last week <b><%= @channel.occurrences.only_public.time_scope('7days').count -%></b>
    </dd>
    <dd>
      <%= image_tag('silk/calendar_view_month.png') -%> Last month <b><%= @channel.occurrences.only_public.time_scope('30days').count -%></b>
    </dd>
    <dd>
      <%= image_tag('silk/calculator.png') -%> Total <b><%= @channel.occurrences.only_public.count -%></b>
    </dd>
    <dd><%= link_to 'Show recent URLs', recent_network_channel_occurrences_path(@channel.network, @channel) -%></dd>
  </dl>
</div>