config/routes.rb
IrcUrls::Application.routes.draw do
  def type(controller, path, viewtype = true)
    interval_constraint = /((\d+)\s?(\w+)|alltime)/
    viewtype_constraint = /(list|grid)/

    scope path do
      match "recent/:viewtype", :to => "#{controller}#recent", :constraints => {:viewtype => viewtype_constraint}, :via => :get if viewtype
      match "top/:interval(/:viewtype)", :to => "#{controller}#index", :constraints => {:viewtype => viewtype_constraint}, :via => :get if viewtype
      match ":viewtype", :to => "#{controller}#index", :constraints => {:viewtype => viewtype_constraint}
      match "top/:interval", :to => "#{controller}#index", :constraints => {:interval => interval_constraint}, :via => :get
    end

    if block_given?
      yield
    else
      match "/", :to => "#{controller}#index"
    end

    resources controller, :path => path, :only => :index do
      collection do
        get :recent
      end
    end

    scope path do
      match "top", :to => "#{controller}#index", :as => "top_#{controller}", :via => :get
    end

  end

  def occurrences(&blk)
    type(:occurrences, "urls", false, &blk)
    type(:video_occurrences, "videos", &blk)
    type(:image_occurrences, "images", &blk)
    type(:media_occurrences, "media", &blk)
  end

  resource :submissions

  match "*anything", :to => redirect("http://irc-urls.net/%{anything}"), :constraints => {:subdomain => "beta"}
  match "/", :to => redirect("http://irc-urls.net/"), :constraints => {:subdomain => "beta"}

  [:images, :videaos, :media].each do |type|
    match "/#{type}/grid/recent", :to => redirect("/#{type}/recent/grid")
  end

  devise_for :users
  resource :token, :only => ["create"]
  match '/account' => 'users#show', :as => 'account'
  match 'help/installation' => "help#installation", :as => "help_installation"

  resources :trackings
  [:url, :image_url, :video_url].each do |type|
    resources type, :path => :url, :controller => :urls, :only => :show
  end

  resources :networks, :only => :index do
    occurrences
    resources :channels, :only => :index do
      occurrences
    end
  end

  resources :caches, :only => :show

  occurrences do
    root :to => "occurrences#index"
  end

end

app/models/network.rb
require "lib/slugify"

class Network < ActiveRecord::Base
  include Slugify
  
  has_many                  :channels, :dependent => :destroy
  has_many                  :occurrences, :through => :channels
  has_many                  :nicks, :dependent => :destroy
  has_many                  :trackings, :through => :channels
  validates_uniqueness_of   :name,    :case_sensitive => false
  validates_presence_of     :name
  validates_format_of       :name,    :with => /^\S+$/
  
  scope :slugified, lambda { |column, str|
    if match = str.match(/^(\d+)-.+/)
      return {:conditions => ["#{self.table_name}.id = ?", match[1]]}
    end
    return {:conditions => ["LOWER(#{self.table_name}.#{column.to_s}) = ?", str.downcase]}
  }

  def to_param
    slugify_if_necessary(id, name)
  end
  
  
  def public_channels
    channels.all(:order => "#{Channel.table_name}.name ASC").select do |c|
      c.public?
    end
  end
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
  before_filter :get_network, :except => [:index]
  
  def show
  end

  def index
    @networks = Network.all(
      :order => "#{Network.table_name}.name ASC"
    )
  end

  private
    def get_network
      @network = Network.slugified(:name, params[:id]).first
    end
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/views/networks/_network.html.erb
<div class="infobox">
  <h2><%= link_to network.name, network_occurrences_path(network) %></h2>
  <ul>
    <%- network.public_channels.each do |channel| %>
      <li><%= link_to channel.name, network_channel_occurrences_path(network, channel) %></li>
    <%- end -%>
  </ul>
</div>

app/views/networks/index.html.erb
<h1><%= title("Networks") -%></h1>

<%- @networks.each do |network| -%>
  <%= render :partial => network if network.public_channels.size > 0 %>
<%- end -%>

app/views/networks/show.html.erb
<h1><%= title("Network #{@network.name}") -%></h1>

<div class="infobox">
  <h2>Statistics</h2>
  <dl>
    <dt>Public URLs<dt>
    <dd>
      <%= image_tag('silk/calendar_view_week.png') -%> Last 24h <b><%= @network.occurrences.only_public.time_scope('24hours').count -%></b>
    </dd>
    <dd>
      <%= image_tag('silk/calendar_view_week.png') -%> Last week <b><%= @network.occurrences.only_public.time_scope('7days').count -%></b>
    </dd>
    <dd>
      <%= image_tag('silk/calendar_view_month.png') -%> Last month <b><%= @network.occurrences.only_public.time_scope('30days').count -%></b>
    </dd>
    <dd>
      <%= image_tag('silk/calculator.png') -%> Total <b><%= @network.occurrences.only_public.count -%></b>
    </dd>
    <dd><%= link_to 'Show recent URLs', recent_network_occurrences_path(@network) -%></dd>
  </dl>
</div>