config/routes.rb
IrcUrls::Application.routes.draw do
  def type(controller, path, viewtype = true)
    interval_constraint = /((\d+)\s?(\w+)|alltime)/
    viewtype_constraint = /(list|grid)/

    scope path do
      match "recent/:viewtype", :to => "#{controller}#recent", :constraints => {:viewtype => viewtype_constraint}, :via => :get if viewtype
      match "top/:interval(/:viewtype)", :to => "#{controller}#index", :constraints => {:viewtype => viewtype_constraint}, :via => :get if viewtype
      match ":viewtype", :to => "#{controller}#index", :constraints => {:viewtype => viewtype_constraint}
      match "top/:interval", :to => "#{controller}#index", :constraints => {:interval => interval_constraint}, :via => :get
    end

    if block_given?
      yield
    else
      match "/", :to => "#{controller}#index"
    end

    resources controller, :path => path, :only => :index do
      collection do
        get :recent
      end
    end

    scope path do
      match "top", :to => "#{controller}#index", :as => "top_#{controller}", :via => :get
    end

  end

  def occurrences(&blk)
    type(:occurrences, "urls", false, &blk)
    type(:video_occurrences, "videos", &blk)
    type(:image_occurrences, "images", &blk)
    type(:media_occurrences, "media", &blk)
  end

  resource :submissions

  match "*anything", :to => redirect("http://irc-urls.net/%{anything}"), :constraints => {:subdomain => "beta"}
  match "/", :to => redirect("http://irc-urls.net/"), :constraints => {:subdomain => "beta"}

  [:images, :videaos, :media].each do |type|
    match "/#{type}/grid/recent", :to => redirect("/#{type}/recent/grid")
  end

  devise_for :users
  resource :token, :only => ["create"]
  match '/account' => 'users#show', :as => 'account'
  match 'help/installation' => "help#installation", :as => "help_installation"

  resources :trackings
  [:url, :image_url, :video_url].each do |type|
    resources type, :path => :url, :controller => :urls, :only => :show
  end

  resources :networks, :only => :index do
    occurrences
    resources :channels, :only => :index do
      occurrences
    end
  end

  resources :caches, :only => :show

  occurrences do
    root :to => "occurrences#index"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :confirmable,
         :recoverable,
         :rememberable,
         :validatable,
         :registerable

  has_many                  :loggings # :dependent => :destroy ??!
  has_many                  :occurrences, :through => :loggings
  has_many                  :trackings, :dependent => :destroy
  has_many                  :channels, :through => :trackings
  has_many                  :permissions, :dependent => :destroy

  validates_presence_of     :login
  validates_length_of       :login, :within => 3..40
  validates_uniqueness_of   :login
  validates_format_of       :login, :with => /\A\w[\w\.\-_@]+\z/
  
  before_create :make_client_key

  attr_accessible :login, :name, :email, :birthdate, :country, :location, :homepage, :password, :password_confirmation

  def self.find_by_client_key(client_key)
    login, dash, secret_key = client_key.rpartition('-')
    User.find_by_login_and_secret_key(login, secret_key)
  end

  def client_key
    "#{self.login}-#{self.secret_key}"
  end

  def regenerate_client_key!
    make_client_key
    self.save!
  end

  protected

  def self.find_for_authentication(conditions)
    conditions = ["login = ? OR email = ?", conditions[authentication_keys.first], conditions[authentication_keys.first]]
    super
  end

  def make_client_key
    self.secret_key = Digest::SHA1.hexdigest("#{Time.now}--#{(1..10).map{ rand.to_s }}")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  #
  # Use this to wrap view elements that the user can't access.
  # !! Note: this is an *interface*, not *security* feature !!
  # You need to do all access control at the controller level.
  #
  # Example:
  # <%= if_authorized?(:index,   User)  do link_to('List all users', users_path) end %> |
  # <%= if_authorized?(:edit,    @user) do link_to('Edit this user', edit_user_path) end %> |
  # <%= if_authorized?(:destroy, @user) do link_to 'Destroy', @user, :confirm => 'Are you sure?', :method => :delete end %> 
  #
  #
  def if_authorized?(action, resource, &block)
    if authorized?(action, resource)
      yield action, resource
    end
  end

  #
  # Link to user's page ('users/1')
  #
  # By default, their login is used as link text and link title (tooltip)
  #
  # Takes options
  # * :content_text => 'Content text in place of user.login', escaped with
  #   the standard h() function.
  # * :content_method => :user_instance_method_to_call_for_content_text
  # * :title_method => :user_instance_method_to_call_for_title_attribute
  # * as well as link_to()'s standard options
  #
  # Examples:
  #   link_to_user @user
  #   # => <a href="/users/3" title="barmy">barmy</a>
  #
  #   # if you've added a .name attribute:
  #  content_tag :span, :class => :vcard do
  #    (link_to_user user, :class => 'fn n', :title_method => :login, :content_method => :name) +
  #          ': ' + (content_tag :span, user.email, :class => 'email')
  #   end
  #   # => <span class="vcard"><a href="/users/3" title="barmy" class="fn n">Cyril Fotheringay-Phipps</a>: <span class="email">barmy@blandings.com</span></span>
  #
  #   link_to_user @user, :content_text => 'Your user page'
  #   # => <a href="/users/3" title="barmy" class="nickname">Your user page</a>
  #
  def link_to_user(user, options={})
    raise "Invalid user" unless user
    options.reverse_merge! :content_method => :login, :title_method => :login, :class => :nickname
    content_text      = options.delete(:content_text)
    content_text    ||= user.send(options.delete(:content_method))
    options[:title] ||= user.send(options.delete(:title_method))
    link_to h(content_text), user_path(user), options
  end

  #
  # Link to login page using remote ip address as link content
  #
  # The :title (and thus, tooltip) is set to the IP address 
  #
  # Examples:
  #   link_to_login_with_IP
  #   # => <a href="/login" title="169.69.69.69">169.69.69.69</a>
  #
  #   link_to_login_with_IP :content_text => 'not signed in'
  #   # => <a href="/login" title="169.69.69.69">not signed in</a>
  #
  def link_to_login_with_IP content_text=nil, options={}
    ip_addr           = request.remote_ip
    content_text    ||= ip_addr
    options.reverse_merge! :title => ip_addr
    if tag = options.delete(:tag)
      content_tag tag, h(content_text), options
    else
      link_to h(content_text), login_path, options
    end
  end

  #
  # Link to the current user's page (using link_to_user) or to the login page
  # (using link_to_login_with_IP).
  #
  def link_to_current_user(options={})
    if current_user
      link_to_user current_user, options
    else
      content_text = options.delete(:content_text) || 'not signed in'
      # kill ignored options from link_to_user
      [:content_method, :title_method].each{|opt| options.delete(opt)} 
      link_to_login_with_IP content_text, options
    end
  end

end

app/views/users/_client_key.html.erb
<p>Your secret client key is:</p>
<pre><%= @user.client_key -%></pre>

app/views/users/show.html.erb
<h1><%= title "User #{h(@user.login)}" -%></h1>
<div class="infobox">
  <h2>Profile</h2>
  <dl>
  <dt>Login<dt><dd><%= h(@user.login) -%></dd>
  <%- unless @user.name.blank? -%>
  <dt>Name<dt><dd><%= h(@user.name) -%></dd>
  <%- end -%>
  <%- unless @user.birthdate.blank? -%>
  <dt>Birthday<dt><dd><%= h(@user.birthdate.to_formatted_s(:long)) -%></dd>
  <%- end -%>
  <%- unless @user.location.blank? -%>
  <dt>Location<dt><dd><%= h(@user.location) -%></dd>
  <%- end -%>
  <%- unless @user.country.blank? -%>
  <dt>Country<dt><dd><%= h(@user.country) -%></dd>
  <%- end -%>
  <%- unless @user.homepage.blank? -%>
   <dt>Blog / Homepage<dt><dd><%= link_to h(@user.homepage), h(@user.homepage) -%></dd>
   <%- end -%>
  </dl>
<%- if current_user == @user # Do not show edit link if not current user -%>
  <p><%= link_to 'Edit profile', edit_user_registration_path -%></p>
<%- end -%>
</div>

<%- if current_user == @user #Start of current user check-%>
<div class="infobox">
  <h2>Channel trackings</h2>
  
  <% if @user.trackings.count > 0 -%>
  <dl>
    <dt>Currently tracking<dt>
    <dd>
      <%= image_tag('silk/world.png') -%> Public channels <b><%= @user.trackings.only_public.count -%></b>
    </dd>
    <dd>
      <%= image_tag('silk/lock.png') -%> Private channels <b><%= @user.trackings.only_private.count -%></b>
    </dd>
    <dd>
      <%= image_tag('silk/stop.png') -%> Untracked channels <b><%= @user.trackings.only_untracked.count -%></b>
    </dd>
  </dl>
  <p><%= link_to 'Edit channel trackings', trackings_path %></p>
  <%- else -%>
  <p>You do not have any trackings. Read <%= link_to "client installation instructions", :controller => :help, :action => :installation -%> to start track channels.</p>
  <%- end -%>
</div>
<%- end #End of current user check for tracking-%>

<div class="infobox">
  <h2>Statistics</h2>
  <dl>
    <dt>URLs logged<dt>
    <dd>
      <%= image_tag('silk/calendar_view_week.png') -%> Last 24h <b><%= @user.occurrences.time_scope('24hours').count -%></b>
    </dd>
    <dd>
      <%= image_tag('silk/calendar_view_week.png') -%> Last week <b><%= @user.occurrences.time_scope('7days').count -%></b>
    </dd>
    <dd>
      <%= image_tag('silk/calendar_view_month.png') -%> Last month <b><%= @user.occurrences.time_scope('30days').count -%></b>
    </dd>
    <dd>
      <%= image_tag('silk/calculator.png') -%> Total <b><%= @user.occurrences.count -%></b>
    </dd>
  </dl>
</div>

<div class="infobox">
  <h2>Client key</h2>
  <div id="client_key">
    <%= render :partial => 'client_key' -%>
  </div>
  <% form_tag token_path, :id => "user-token-form" do %>
    <div class="buttons"><%= submit_button do
      image_tag("silk/textfield_key.png", :alt => "") + 'Regenerate key'
    end %>
    </div>
  <% end %>
  <p>Note: You have to update new key in your IRC client</p>
</div>

<% content_for :js do %>
  <script type="text/javascript">
    $(document).ready(function() {
      $("#user-token-form").submit(function() {
        $.post("<%= token_path %>", function(token) {
          console.log(token);
          $("#client_key > pre").text(token);
        }, "json");
        return false;
      });
    })
  </script>
<% end%>