config/routes.rb
IrcUrls::Application.routes.draw do
  def type(controller, path, viewtype = true)
    interval_constraint = /((\d+)\s?(\w+)|alltime)/
    viewtype_constraint = /(list|grid)/

    scope path do
      match "recent/:viewtype", :to => "#{controller}#recent", :constraints => {:viewtype => viewtype_constraint}, :via => :get if viewtype
      match "top/:interval(/:viewtype)", :to => "#{controller}#index", :constraints => {:viewtype => viewtype_constraint}, :via => :get if viewtype
      match ":viewtype", :to => "#{controller}#index", :constraints => {:viewtype => viewtype_constraint}
      match "top/:interval", :to => "#{controller}#index", :constraints => {:interval => interval_constraint}, :via => :get
    end

    if block_given?
      yield
    else
      match "/", :to => "#{controller}#index"
    end

    resources controller, :path => path, :only => :index do
      collection do
        get :recent
      end
    end

    scope path do
      match "top", :to => "#{controller}#index", :as => "top_#{controller}", :via => :get
    end

  end

  def occurrences(&blk)
    type(:occurrences, "urls", false, &blk)
    type(:video_occurrences, "videos", &blk)
    type(:image_occurrences, "images", &blk)
    type(:media_occurrences, "media", &blk)
  end

  resource :submissions

  match "*anything", :to => redirect("http://irc-urls.net/%{anything}"), :constraints => {:subdomain => "beta"}
  match "/", :to => redirect("http://irc-urls.net/"), :constraints => {:subdomain => "beta"}

  [:images, :videaos, :media].each do |type|
    match "/#{type}/grid/recent", :to => redirect("/#{type}/recent/grid")
  end

  devise_for :users
  resource :token, :only => ["create"]
  match '/account' => 'users#show', :as => 'account'
  match 'help/installation' => "help#installation", :as => "help_installation"

  resources :trackings
  [:url, :image_url, :video_url].each do |type|
    resources type, :path => :url, :controller => :urls, :only => :show
  end

  resources :networks, :only => :index do
    occurrences
    resources :channels, :only => :index do
      occurrences
    end
  end

  resources :caches, :only => :show

  occurrences do
    root :to => "occurrences#index"
  end

end

app/views/shared/_datepicker.html.haml
.group
  = image_tag "silk/time.png"
  = link_to create_occurrence_hash(params.merge(:date => (@date - 1.day ))), :class => "img button" do
    = image_tag "silk/control_rewind_blue.png", :alt => "Previous day"
  = form_tag '', :method => :get do
    = text_field_tag 'date', (params[:date] || Time.now.strftime("%Y-%m-%d")), :id => 'datepicker'
  = link_to create_occurrence_hash(params.merge(:date => (@date + 1.day ))), :class => "img button" do
    = image_tag "silk/control_fastforward_blue.png", :alt => "Next day"

app/views/shared/_filters.html.haml
#filters
  - if params[:action].to_s.downcase == 'index'
    = render :partial => 'shared/interval_options'
  - else
    = render :partial => "shared/datepicker"
  - if @show_view_options
    = render :partial => 'shared/view_options'
  - if @network && !params[:channel_id]
    .group
      %p
        Showing all channels at
        %strong #{@network.name}
        —
        = link_to "show all", create_occurrence_hash(params.merge(:network_id => nil))
  - if params[:channel_id]
    .group
      %p
        Showing
        %strong= @channel.name rescue Channel.real_name(params[:channel_id])
        —
        = link_to "show_all", create_occurrence_hash(params.merge(:channel_id => nil, :network_id => nil))
  = render :partial => "shared/search"

app/views/shared/_header.html.haml
#hat
  %a{:href => root_path}= image_tag "irc-urls_logo.png", :alt => "IRC-URLs"
  %span= link_to "How to track channels?", help_installation_path
  %span= render :partial => "shared/user_bar"

app/views/shared/_interval_options.html.haml
.group
  = image_tag "silk/time.png"
  %ul
    %li{:class => ("active" if interval == 1.hour)}
      = link_to '1h', create_occurrence_hash(params.merge(:interval => '1hour', :page => nil))
    %li{:class => ("active" if interval == 24.hours)}
      = link_to '24h', create_occurrence_hash(params.merge(:interval => '24hours', :page => nil)), :class => "active"
    %li{:class => ("active" if interval == 3.days)}
      = link_to '3d', create_occurrence_hash(params.merge(:interval => '3days', :page => nil))
    %li{:class => ("active" if interval == 30.days)}
      = link_to '30d', create_occurrence_hash(params.merge(:interval => '30days', :page => nil))
    %li{:class => ("active" if params[:interval] == "alltime")}
      = link_to 'All', create_occurrence_hash(params.merge(:interval => 'alltime', :page => nil))

app/views/shared/_navigation.html.haml
%nav
  %ul.tabs
    %li
      = link_to_unless_current "Most popular #{@media_title}", create_occurrence_hash(params.merge(:action => :index)) do
        = link_to "Most popular #{@media_title}", create_occurrence_hash(params.merge(:action => :index)), {:class => 'current'}
    %li
      = link_to_unless_current "Recent #{@media_title}", create_occurrence_hash(params.merge(:action => :recent, 'interval' => nil, :date => nil)) do
        = link_to "Recent #{@media_title}", create_occurrence_hash(params.merge(:action => :recent, 'interval' => nil, :date => nil)), {:class => 'current'}
  %ul.categories
    %li
      = link_to_unless_current "All", create_occurrence_hash(params.merge(:controller => "/occurrences", 'viewtype' => nil, :action => params[:action])) do
        = link_to "All", create_occurrence_hash(params.merge(:controller => "/occurrences", 'viewtype' => nil, :action => params[:action])), {:class => 'current'}
    %li
      = link_to_unless_current "Images", create_occurrence_hash(params.merge(:controller => "/image_occurrences", :action => params[:action])) do
        = link_to "Images", create_occurrence_hash(params.merge(:controller => "/image_occurrences", :action => params[:action])), {:class => 'current'}
    %li
      = link_to_unless_current "Videos", create_occurrence_hash(params.merge(:controller => "/video_occurrences", :action => params[:action])) do
        = link_to "Videos", create_occurrence_hash(params.merge(:controller => "/video_occurrences", :action => params[:action])), {:class => 'current'}
    %li
      = link_to_unless_current "All media", create_occurrence_hash(params.merge(:controller => "/media_occurrences", :action => params[:action])) do
        = link_to "All media", create_occurrence_hash(params.merge(:controller => "/media_occurrences", :action => params[:action])), {:class => 'current'}

app/views/shared/_search.html.haml
- if params[:search]
  .group
    %p
      %strong= pluralize(@occurrences.total_entries, "result")
      for
      %strong= params[:search]
      —
      = link_to "clear search", create_occurrence_hash(params.merge(:search => nil))
#searchcontainer
  = form_tag '', :method => :get do
    = text_field_tag 'search', params[:search]
    = submit_button({:class => "primary"}) do
      = image_tag("silk/magnifier.png", :alt => "Search")

app/views/shared/_user_bar.html.haml
= image_tag 'silk/user.png', :class => 'icon'
- if user_signed_in?
  Logged in as
  = link_to current_user.login, account_path
  (
  = link_to 'Sign out', destroy_user_session_path
  )
- else
  = link_to "Not logged in", user_session_path
  —
  = link_to "Sign in", new_user_session_path, :title => "Login"
  \/
  = link_to "Sign up", new_user_registration_path, :title => "Create an account"

app/views/shared/_view_options.html.haml
.group
  = image_tag "silk/eye.png", :alt => "View", :title => "View"
  %ul
    %li{:class => ("active" if params[:viewtype] != "list")}
      = link_to "Grid view",  params.merge(:viewtype => nil, :page => nil), {:class => "current imgbutton", :id => "gridbutton"}
    %li{:class => ("active" if params[:viewtype] == "list")}
      = link_to "List", params.merge(:viewtype => 'list', :page => nil), {:class => "current imgbutton", :id => "listbutton"}